### PR TITLE
docs: add kotlin examples for @Daijishou/RetroAchievements-Kotlin

### PR DESCRIPTION
**Pull request by official-wizard**
This request is to add Kotlin examples for @Daijishou/RetroAchievements-Kotlin

### CODE REVIEW

**Comment by wescopeland** [comment]
Hi @official-wizard! Thank you for opening a PR into api-docs. After a cursory glance of the potential contribution here, I can attest that it appears to be high quality. I would expect no less 😊

I must apologize. We may be at something of an impasse with this PR. The intention of api-docs is to document client libraries that live and are officially maintained by the RetroAchievements organization. These official libraries (of which only one has been publicly released, with another in development) closely track RAWeb's implementation details and receive updates when those implementation details change. Consumers can place their confidence in us that we'll keep that release cycle going.

Currently, `@Daijishou/RetroAchievements-Kotlin` is not an official library, and therefore we likely cannot place it in our official docs. Doing so may confuse consumers if we did indeed have an `api-kotlin` library one day which we wanted to support and document.

If you are interested in `@Daijishou/RetroAchievements-Kotlin` becoming an official RA library (`RetroAchievements/api-kotlin`), that is certainly a conversation we can have.

**Comment by official-wizard** [comment]
That's completely understandable, I had entirely made this to help out Daijishou in accelerating the process for them. Then caught the mention that we should push this into the docs for broader use. 

I can see that being a concern though, and wouldn't mind with going through the process of this being maintained through the official org to have a reliable synchronized cycle between the libraries that's guaranteed on your end. 🚀 let me know how we should go about this.

**Comment by wescopeland** [comment]
We would definitely be interested in pursuing an official relationship and having `@Daijishou/RetroAchievements-Kotlin` evolve into `RetroAchievements/api-kotlin`.

I've cloned the Kotlin repo to take a look. It aligns very well with our strategy of client libraries introducing little to no magic/abstractions, and keeping things very thin. Great job! The "reference wrapper" approach makes it much easier to keep the package up to date when something in RAWeb changes which impacts the API.

I see that the Kotlin package uses the Apache 2.0 license. To move forward, we'd likely request this be changed to either GPL 3 or MIT.

Additionally, we'd like to see some tests added to the package. For comparison, `api-js` has roughly 90%+ statement coverage and 80%+ branch coverage. It is conceivable that for each of our client packages, at some point in the distant future, someone other than us (the original authors) will need to maintain it. Those maintainers may not necessarily be well-versed in the language that the package is written in. Tests can guide and protect them, as well as the package consumers.

Let me know how all this sounds. We'd love to work with you to make `api-kotlin` a reality.

**Comment by official-wizard** [comment]
Thank you! ❤️‍🔥 
I went ahead and added unit testing & have transitioned the license to MIT, let me know what you guys think 😃

**Comment by TapiocaFox** [comment]
@official-wizard, @wescopeland Hi!

 I would agree with the transition to `RetroAchievements/api-kotlin`. And thanks for the works of @official-wizard.

**Comment by wescopeland** [comment]
Hi @official-wizard!

We've set up an `api-kotlin` repo, and you should have write privileges to it.
Additionally, I am going to shoot to finish the modernization of `api-docs` today. It's going to cause some conflicts in this branch, but we'll get them fixed. I'm also going to get the README for `api-js` updated.

**Pull request closed without merging**
